### ISSUE TITLE
Each bundle should group same priced games together

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#109] opened 2022-02-21 22:58 UTC
https://imgur.com/a/ySqLfI5

For example, in this image 'Doom' and 'Sam's Test Game' should group together under a £10 heading or something.

Ideally each bundle should be split into sections like:

'Donate £5 or more to receive:'
Item 1
Item 2

'Donate £10 or more to receive:'
All the above + 
Item 3
Item 4

'Donate £25 or more to receive:'
All the above +
Item 5
Item 6

etc

---

I tried recreating multiple bundles to test this, rather than setting the price of games individually within a bundle, but realised that when you create a new bundle, keys won't get assigned to existing donators and none of the existing donators will have 'purchased' the new bundle. So basically a new bundle can't be created once an event is underway as existing donators won't receive it (which is fine! just need to know!)

**Comment by elliotcm** [comment] 2022-02-22 19:22
Looks like this is two tickets, could you split it up?

The first one is a small enhancement, but I'd postpone it until after we have the new frontend.

The second one I can confirm is true, but would not be too hard to rectify.  As mentioned elsewhere we should (and hopefully will) have periodic background tasks which check all bundle definitions against all donations and make assignments accordingly.  We can always trigger this by hand right now if needed.

Relatedly, this does work if you modify a bundle, just doesn't happen automatically for new bundle definitions.

**Comment by elliotcm** [comment] 2022-04-06 15:05
Closed in favour of https://github.com/SmartCasual/jingle-jam/issues/124 and https://github.com/SmartCasual/jingle-jam/issues/123

**Closed by elliotcm** 2022-04-06 15:05 UTC
Labels: Needs clean up
